<!DOCTYPE html>
<html lang="en-US">
  <head>

    
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-132097591-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-132097591-1');
      </script>
    
    <meta charset="UTF-8">


<!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Arjun Bakshi</title>
<meta name="generator" content="Jekyll v3.9.2" />
<meta property="og:title" content="Arjun Bakshi" />
<meta property="og:locale" content="en_US" />
<link rel="canonical" href="https://abaxi.github.io/" />
<meta property="og:url" content="https://abaxi.github.io/" />
<meta property="og:site_name" content="Arjun Bakshi" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Arjun Bakshi" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebSite","headline":"Arjun Bakshi","name":"Arjun Bakshi","url":"https://abaxi.github.io/"}</script>
<!-- End Jekyll SEO tag -->
